### ISSUE TITLE
[BUG] - SyntaxError with cyrilic named effect/spell

### ISSUE THREAD

**Issue by Emwi-zzz** [fantasycalendar/FoundryVTT-Sequencer#257]
I'm getting

```
caught (in promise) SyntaxError: undefined. Invalid regular expression: /^\л\е\д\я\н\о\и\л\у\ч\/rayoffrost$/: Invalid escape (at sequencer-effect-manager.js:198:23)
[Detected 2 packages: sequencer, autoanimations]
    at new RegExp (<anonymous>)
    at SequencerEffectManager._filterEffects (sequencer-effect-manager.js:198:23)
    at SequencerEffectManager.getEffects (sequencer-effect-manager.js:76:17)
    at AAHandler.fakeSource (workflow-data.js:237:54)
    at DataSanitizer.setPrimaryOptions (DataSanitizer.js:168:43)
    at DataSanitizer.compilePrimary (DataSanitizer.js:98:27)
    at DataSanitizer._getAnimationData (DataSanitizer.js:14:96)
    at trafficCop$1 (traffic-cop.js:19:47)
    at attack$1 (aa-dnd5e.js:84:5)
```
and effect doesnt appear, I'm using Automated animation

1. Attack with a weapoon/spell named using cyrillic

I expected to see an "Ray of Frost" animation

When i renamed my spell using only ASCII, I got a correct response(animation has started)

### Versions:

Foundry 11 Stable 315
DnD 3.2.0
Sequencer 3.2.10

amd some more unnecessary mods in this context

**Comment by Haxxer** [comment]
Fixed in 3.2.11
