### ISSUE TITLE
[BUG] - Screen Space Above UI broken

### ISSUE THREAD

**Issue by ChasarooniZ** [fantasycalendar/FoundryVTT-Sequencer#299]
![image](https://github.com/user-attachments/assets/7a69635f-ef47-4f01-81bc-27ab190f7102)

**Comment by ChasarooniZ** [comment]
Hi sorry, let me confirm that is enabled as it could be the issue

**Comment by ChasarooniZ** [comment]
![image](https://github.com/user-attachments/assets/bcc5f0fa-f188-4b44-8500-76f4d57a27f5)
yes it is enabled, lemme try again with debug settings and i'll get you the code that broke with it as well

**Comment by ChasarooniZ** [comment]
```js
{
    "_id": "nmFg5jz6tyZDHSrt",
    "flagVersion": "3.2.1",
    "sequenceId": "3gOu9GqEwJcnleoF",
    "creationTimestamp": 1724183404824,
    "sceneId": "ECzbSoQ8U00R5XBD",
    "creatorUserId": "J3oConv1eQRLao6j",
    "moduleName": "Sequencer",
    "users": [
        "J3oConv1eQRLao6j",
        "fjycnT1qQHXG0cKs",
        "1O3RAI7mDaTYAHeV",
        "MA0p3cYMluWfvIPp",
        "ipa9MC553dUE7TPo",
        "R94AfZioDR9vd06Y",
        "YS8yb2BiPHt0Dzds"
    ],
    "name": null,
    "origin": null,
    "index": 2,
    "repetition": 0,
    "private": null,
    "temporary": false,
    "tiedDocuments": [],
    "source": null,
    "target": false,
    "rotateTowards": null,
    "stretchTo": false,
    "moveTowards": false,
    "attachTo": null,
    "missed": null,
    "file": "",
    "customRange": false,
    "forcedIndex": false,
    "fileOptions": false,
    "text": null,
    "tilingTexture": null,
    "masks": [],
    "shapes": [
        {
            "lineSize": 0,
            "width": 1920,
            "height": 129.6,
            "fillColor": 6883079,
            "fillAlpha": 1,
            "name": "feCritA",
            "type": "rectangle"
        }
    ],
    "volume": null,
    "isometric": null,
    "syncGroup": "fe-crit-Scene.ECzbSoQ8U00R5XBD.Token.n2yJ0mhDlOYKIgBD",
    "scale": {
        "x": 1,
        "y": 1
    },
    "spriteScale": {
        "x": 1,
        "y": 1
    },
    "angle": null,
    "size": null,
    "offset": null,
    "anchor": null,
    "spriteOffset": null,
    "spriteAnchor": null,
    "template": null,
    "zeroSpriteRotation": null,
    "randomOffset": null,
    "randomRotation": null,
    "scaleToObject": null,
    "elevation": null,
    "sortLayer": 800,
    "aboveLighting": null,
    "aboveInterface": null,
    "xray": null,
    "zIndex": -1,
    "opacity": 0.7,
    "filters": null,
    "loopOptions": null,
    "spriteRotation": 0,
    "randomSpriteRotation": false,
    "flipX": null,
    "flipY": null,
    "duration": 1000,
    "persist": null,
    "persistOptions": null,
    "playbackRate": null,
    "extraEndDuration": null,
    "time": false,
    "moves": null,
    "moveSpeed": null,
    "fadeIn": null,
    "fadeOut": null,
    "scaleIn": null,
    "scaleOut": null,
    "rotateIn": null,
    "rotateOut": null,
    "fadeInAudio": null,
    "fadeOutAudio": null,
    "animations": [
        {
            "target": "shapes.feCritA",
            "propertyName": "scale.y",
            "from": 1,
            "to": 0.6,
            "duration": 1000,
            "delay": 0,
            "ease": "easeInCubic",
            "looping": false,
            "fromEnd": false,
            "gridUnits": false,
            "absolute": false
        },
        {
            "target": "shapes.feCritA",
            "propertyName": "position.y",
            "from": 0,
            "to": 25.92,
            "duration": 1000,
            "delay": 0,
            "ease": "easeInCubic",
            "looping": false,
            "fromEnd": false,
            "gridUnits": false,
            "absolute": false
        }
    ],
    "screenSpace": true,
    "screenSpaceAboveUI": true,
    "screenSpaceAnchor": {
        "x": 0,
        "y": 0.5
    },
    "screenSpacePosition": {
        "x": 0,
        "y": -64.8
    },
    "screenSpaceScale": null,
    "nameOffsetMap": false
}
```

**Comment by Codas** [comment]
Seems like something is up with the shader and the above ui layer..?

I'll take a look :)

```
Uncaught (in promise) TypeError: undefined. Cannot read properties of null (reading 'generateShader')
[Detected 2 packages: sequencer(3.2.16), lib-wrapper(1.12.15.0)]
    at BatchPlugin.onPrerender (foundry.js:42360:43)
    at o.emit (index.js:201:33)
    at xn.render (ObjectRendererSystem.ts:70:18)
    at ea.render (Renderer.ts:377:29)
    at na.render (Application.ts:90:23)
    at na.resize (ResizePlugin.ts:139:18)
    at na.set (ResizePlugin.ts:59:30)
    at new SequencerAboveUILayer (effects-layer.js:460:14)
    at SequencerAboveUILayer.setup (effects-layer.js:466:13)
    at initializeModule (module.js:144:25)
    at Object.fn (module.js:45:3)
    at #call (foundry.js:608:20)
    at Hooks.callAll (foundry.js:565:17)
    at Game.initialize (foundry.js:8885:11)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁libWrapperInit (libWrapper-api.js:805:11)
foundry.js:42360 Uncaught TypeError: undefined. Cannot read properties of null (reading 'generateShader')
[No packages detected]
    at BatchPlugin.onPrerender (foundry.js:42360:43)
    at o.emit (index.js:201:33)
    at xn.render (ObjectRendererSystem.ts:70:18)
    at ea.render (Renderer.ts:377:29)
    at na.render (Application.ts:90:23)
    at mn.emit (TickerListener.ts:67:25)
    at Pt.update (Ticker.ts:427:37)
    at Pt._tick (Ticker.ts:129:22)
```
